# Generated by Django 5.1 on 2024-08-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_height_products_length_products_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='main_foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/main_product_images/'),
        ),
    ]
