# Generated by Django 5.1 on 2024-08-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_main_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='main_foto',
            field=models.ImageField(blank=True, null=True, upload_to='main_product_images'),
        ),
    ]
