# Generated by Django 5.1.1 on 2024-09-11 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_basket_height_basket_length_basket_main_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='order_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
