# Generated by Django 5.1.1 on 2024-09-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_favouriteproducts_category_favouriteproducts_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_mini',
            field=models.ImageField(blank=True, null=True, upload_to='mini_product_images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
