# Generated by Django 5.1.1 on 2024-09-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productimage_image_mini_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
