# Generated by Django 5.1.1 on 2024-09-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteproducts',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
