# Generated by Django 5.1.1 on 2024-10-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='sub_category',
            field=models.ManyToManyField(to='products.subcategory'),
        ),
    ]
