# Generated by Django 5.1.1 on 2024-10-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_categories_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons'),
        ),
    ]
